remote-theme: hu-zza/hu-zza.github.io

# Site settings
baseurl: 'https://hu-zza.github.io'
canonicalurl: 'https://zza.hu'
title: 'Szabó László András // hu-zza'
keywords: 'Szabó László András, hu-zza, μBot, Java'
description: 'This is a link collection about me: My Java and other (μBot) projects, social pages, etc.'
background: '/images/cover.jpg'
font_awesome: '03e56b669f.js'

author:
    fullName: 'Szabó László András // hu-zza'
    firstName: 'László András'
    lastName: 'Szabó'
    username: 'hu-zza'
    gender: 'male'
    picture:
        link: '/images/profile.jpg'
        url: 'http://hu-zza.github.io/images/profile.jpg'
        secureUrl: 'https://hu-zza.github.io/images/profile.jpg'
        type: 'image/jpeg'
        width: '512'
        height: '512'
        title: 'Me and my darling :-)'
    description: 'Making beta tests at JetBrains Academy, working on the project&nbsp;<a href="https://zza.hu/uBot"
                  target="_blank" class="inline-link" title="Link to the project page of the μBot">μBot</a> and
                  learning Java, Spring, JUnit,&nbsp;... 24/7 ;-) <a href="https://whoami.zza.hu" class="inline-link"
                  title="Link to my full introduction">Read my introduction</a>'
    github_username: 'hu-zza'
    linkedin_username: 'hu-zza'
    credly_username: 'hu-zza'

    highlight:
        title: 'Link to the project page of the μBot'
        url: 'https://zza.hu/uBot'
        txt:
            content: '<i class="fas fa-child fa-lg"></i>&nbsp;μBot'
            style: ''
        abbr:
            content: 'μ'
            style: 'font-size: 19px; height: 20px;'


# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md']
